### PR TITLE
Should we add a folder like this?

### PR DESCRIPTION
**Pull request by sarambl**
Should we add a folder like this?

### CODE REVIEW

**Comment by duncanwp** [comment]
Yes, I like the idea. I wonder if we should have folders for 'proposed', 'running' and 'completed' ? Then maybe this folder is 'proposed'?

**Comment by sarambl** [comment]
I also added a description of how to upload experiments in the readme.

**Comment by sarambl** [comment]
Yes, @duncanwp , that's actually a very good idea. Should I just go ahead and restructure it?

**Comment by duncanwp** [comment]
Yes please!

**Review by duncanwp — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
